hiero-ledger/hiero-gradle-conventions

- src/main/kotlin/org.hiero.gradle.feature.publish-maven-repository.gradle.kts
**Description**: Updates the publish-maven-repository gradle file to include the project name. This is required for schema validation within maven central.
**Related Issue(s)**:
Fixes #3
> fix: Added name field in pom generation

- src/main/kotlin/org.hiero.gradle.feature.publish-maven-repository.gradle.kts
The `<description></description>` field was not present in the pom.xml file generated for maven central. Needed to update two parts of the field setter:
- `.orElse(provider { project.description })` became `.orElse(provider(project::getDescription))` to actually populate with the project description
- `.orNull()` becomes `.orElse("")` to prevent a null entry on description if it is not present in the other ways
> fix(bug): Update description setters

- src/main/kotlin/org.hiero.gradle.base.jpms-modules.gradle.kts
See: https://github.com/hashgraph/hedera-sdk-java/pull/2059#issuecomment-2488506421
> chore: change Module Name to official name 'com.esaulpaugh.headlong'

- build.gradle.kts
- src/main/kotlin/org.hiero.gradle.feature.publish-maven-repository.gradle.kts
See: https://github.com/hashgraph/hedera-services/issues/16548
> build: always sign via useGpgCmd()

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-build-plugins.yaml
Updates workflows to avoid step-security maintained actions as we don't have a license configured with them yet.
Configured a hiero-ledger version of the network-node runners
Moved runners from gh hosted to self-hosted
**Related Issue(s)**:
Fixes #23
> chore: Update actions and runs-on stanzas.

- src/main/kotlin/org.hiero.gradle.check.spotless-yaml.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/ConventionPluginTest.kt
- src/test/kotlin/org/hiero/gradle/test/QualityGateTest.kt
- src/test/kotlin/org/hiero/gradle/test/fixtures/GradleProject.kt
See https://github.com/hiero-ledger/hiero-gradle-conventions/issues/30#issuecomment-2530730664
> build: include '*.yml' files

- README.md
- developers.properties
- example/product-a/developers.properties
- src/main/kotlin/org.hiero.gradle.feature.publish-maven-repository.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/MavenCentralPublishTest.kt
- src/test/kotlin/org/hiero/gradle/test/fixtures/GradleProject.kt
> build: replace 'developer.properties' with generic Hiero entry

- CHANGELOG.md
- src/main/kotlin/org.hiero.gradle.feature.publish-artifactregistry.gradle.kts
There was an issue where releasePrereleaseChannel was attempting to use the artifactregistry plugin when it should not. The resolution is to add a condition to an if-check to resolve this issue.
**Related Issue(s)**:
Fixes #55
> build: fix issue caused by interaction with releasePrereleaseChannel and publish-artifactregistry

- src/main/kotlin/org.hiero.gradle.check.spotless-java.gradle.kts
- src/main/kotlin/org/hiero/gradle/spotless/LicenseHeader.kt
- src/test/kotlin/org/hiero/gradle/test/QualityGateTest.kt
> build: add license header to 'module-info' and 'package-info'

- src/main/kotlin/org.hiero.gradle.base.jpms-modules.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/JpmsPatchTest.kt
This is used by the latest Dagger version.
> build: add patch rule for 'com.squareup:kotlinpoet-jvm'

- src/main/kotlin/org.hiero.gradle.feature.publish-maven-repository.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/LocalPublishTest.kt
- src/test/kotlin/org/hiero/gradle/test/MavenCentralPublishTest.kt
- src/test/kotlin/org/hiero/gradle/test/PublishDependencyConstraintsTest.kt
...including Gradle plugins, for which '-PpublishSigningEnabled' had no effect.
> build: deactivate signing by default for everything that is published

- CHANGELOG.md
- src/main/descriptions/org.hiero.gradle.feature.legacy-classpath.txt
- src/main/kotlin/org.hiero.gradle.feature.legacy-classpath.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/LegacyClasspathTest.kt
- src/test/kotlin/org/hiero/gradle/test/fixtures/GradleProject.kt
> build: add 'feature.legacy-classpath' plugin

- CHANGELOG.md
- src/main/kotlin/org.hiero.gradle.feature.protobuf.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/ProtobufTest.kt
> build: track tool versions as input of generateProto task

- src/main/kotlin/org.hiero.gradle.base.jpms-modules.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/JpmsPatchTest.kt
With version 24.7.1 besu introduced new dependency of org.hyperledger.besu.nativelib.gnark so we need to include that module.
**Related issue(s)**:
Fixes #
[#17572](https://github.com/hiero-ledger/hiero-consensus-node/issues/17572)
**Notes for reviewer**:
**Checklist**
> build: add patching rules for 'org.hyperledger.besu.nativelib.gnark'

- src/main/kotlin/org.hiero.gradle.base.jpms-modules.gradle.kts
Adds:
- io.prometheus.metrics.shaded.protobuf
- micrometer.registry.prometheus.simpleclient
**Related issue(s)**:
Fixes #130
> build: add more rules for transitive dependencies of helidon

- .github/workflows/zxc-build-plugins.yaml
Replaced EnricoMi/publish-unit-test-result-action with step-security version
**Related issue(s)**:
Fixes #155 
**Notes for reviewer**:
**Checklist**
> ci: replace action with step-security maintained version

- CHANGELOG.md
- src/main/kotlin/org.hiero.gradle.base.jpms-modules.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/JpmsPatchTest.kt
- The way we did it was not really the right solution (see discussion in https://github.com/netty/netty/issues/15003)
- The problem has been resolved in Netty `4.2.1.Final` - hence we remove the rule altogether
> build: remove Netty patch rules

- README.md
- build.gradle.kts
- src/main/descriptions/org.hiero.gradle.feature.publish-maven-central-aggregation.txt
- src/main/kotlin/org.hiero.gradle.feature.publish-maven-central-aggregation.gradle.kts
- src/main/kotlin/org.hiero.gradle.feature.publish-maven-central.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/MavenCentralPortalPublishTest.kt
- src/test/kotlin/org/hiero/gradle/test/fixtures/GradleProject.kt
The idea is that you then have both mechanisms available (until the old one can be retired for good).
The new mechanism works through the `gradle/aggregation` project, which is more consistent with how we aggregate build results in other cases (e.g. reports). Everything that is going to be published is collected in one `zip` that is then updated.
In the projects, we need to adjust the `gradle/aggregation/build.gradle.kts` as folldows:
```
plugins {
...
id("org.hiero.gradle.feature.publish-maven-central-aggregation") // add new aggregated publish
}
dependencies {
// all projects that are to be published are part of the new "published" scope
published(project(":app"))
published(project(":hedera-protobuf-java-api"))
// examples.. not published! …
```
> build: add com.gradleup.nmcp for Maven Central publishing

- src/main/kotlin/org.hiero.gradle.feature.java-execute.gradle.kts
- src/test/kotlin/org/hiero/gradle/test/ExecuteTest.kt
**Related issue(s)**:
Resolves #199
> build: switch the default for JavaExec.inferModulePath back to true

- src/main/kotlin/org.hiero.gradle.base.jpms-modules.gradle.kts
Reverts: #225 
Required for: https://github.com/hiero-ledger/hiero-consensus-node/pull/19951
This is also needed to make the `JpmsPatchTest` that is currently failing on all branches, as it tests all patched libraries against the latest stable version.
> build: remove patching for Eclipse Collections

- src/main/kotlin/org.hiero.gradle.feature.publish-artifactregistry.gradle.kts
...because the sonatype plugin was removed in the previous release in #230.
Without this fix, GC publishing now fails with:
```
> Failed to apply plugin 'org.hiero.gradle.feature.publish-artifactregistry'.
> Repository with name 'sonatype' not found.
```
> build: 'cloud.artifactregistry' no longer interacts with sonatype plugin

- src/main/kotlin/org.hiero.gradle.feature.publish-maven-central-aggregation.gradle.kts
Increase the Maven Central publishing timeout to 1 hour.
**Related Issue(s)**:
Fixes #244
Fixes #245
> chore: increase Maven Central publishing timeout to 1 hour

- src/main/kotlin/org.hiero.gradle.check.spotless.gradle.kts
The `mustRunAfter` can cause a cycle with code generation and multiple source sets that have dependencies between each other. The code generation of one project than many need the Jar from another project. For that, the other project needs to be compiled first. But as the spotless formatting is done in one task for **all** source sets, it cannot both run **after** the compilation of all source sets and **before** the code generation of all source sets.
This was discovered working on https://github.com/hashgraph/pbj/pull/595
```
Circular dependency between the following tasks:
ExtraJavaModuleInfoTransform
\--- :jar
+--- :classes
|    \--- :compileJava
|         \--- :spotlessApply
|              +--- :spotlessJavaApply
|              |    \--- :spotlessJava
| …
```
> build: mustRunAfter -> shouldRunAfter in spotless setup
